# Generated by Django 3.1.5 on 2021-02-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='subscription',
            field=models.CharField(blank=True, choices=[('Standart', 'Standart'), ('VIP', 'VIP'), ('Premium', 'Premium')], default='Standart', max_length=250, verbose_name='sub'),
        ),
    ]
